[package]
name = "tacview_live"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
bevy_http_client = "0.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1"
url = "2"